### ISSUE TITLE
Catalog from_file showing not working  

### ISSUE THREAD

**Issue by sulabh9999** [azavea/pystac#64]
source code:
```
from pystac import Catalog
cat = Catalog.from_file('https://sentinel-stac.s3.amazonaws.com/catalog.json'))
```
showing error:
Traceback (most recent call last):
  File "source/main.py", line 5, in <module>
    cat = Catalog.from_file('https://sentinel-stac.s3.amazonaws.com/catalog.json')
  File "/home/nawaz/Documents/disaster_managment/venv/lib/python3.6/site-packages/pystac/stac_object.py", line 408, in from_file
    d = STAC_IO.read_json(href)
  File "/home/nawaz/Documents/disaster_managment/venv/lib/python3.6/site-packages/pystac/stac_io.py", line 99, in read_json
    return json.loads(STAC_IO.read_text(uri))
  File "/home/nawaz/Documents/disaster_managment/venv/lib/python3.6/site-packages/pystac/stac_io.py", line 64, in read_text
    return cls.read_text_method(uri)
  File "/home/nawaz/Documents/disaster_managment/venv/lib/python3.6/site-packages/pystac/stac_io.py", line 14, in default_read_text_method
    with open(uri) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'https://sentinel-stac.s3.amazonaws.com/catalog.json'

**Comment by lossyrob** [comment]
Hi @sulabh9999,

Did you happen to use the instructions [here](https://pystac.readthedocs.io/en/latest/concepts.html#using-stac-io) to enable reading from HTTPS? If not, can you give it a try and see if it solves your problem? Thanks!

**Comment by sulabh9999** [comment]
Thanks .. it's working fine.
