### ISSUE TITLE
Error when saving and then loading Catalog

### ISSUE THREAD

**Issue by lewfish** [azavea/pystac#88]
Using PySTAC 0.3.3, the following code executed as a script works as expected (it saves a STAC and then opens it and prints the items). But if you uncomment the code in Block A, Line B will fail with the following stack trace. This especially strange because all that Block A does is read from the catalog before saving it. This came up in the context of trying to modify some links to GeoTIFF files in an existing stack, and then saving the modified copy. I found that the following was the minimal example that replicates the error.

```python
from urllib.parse import urlparse
from os.path import join

import boto3
from pystac import STAC_IO
from pystac import Catalog, LabelItem, CatalogType

# Copied from PyStac tutorial.
def setup_stac_s3():
    def my_read_method(uri):
        parsed = urlparse(uri)
        if parsed.scheme == 's3':
            bucket = parsed.netloc
            key = parsed.path[1:]
            s3 = boto3.resource('s3')
            obj = s3.Object(bucket, key)
            return obj.get()['Body'].read().decode('utf-8')
        else:
            return STAC_IO.default_read_text_method(uri)

    def my_write_method(uri, txt):
        parsed = urlparse(uri)
        if parsed.scheme == 's3':
            bucket = parsed.netloc
            key = parsed.path[1:]
            s3 = boto3.resource("s3")
            s3.Object(bucket, key).put(Body=txt)
        else:
            STAC_IO.default_write_text_method(uri, txt)

    STAC_IO.read_text_method = my_read_method
    STAC_IO.write_text_method = my_write_method

# Open a catalog and then save a copy locally.
setup_stac_s3()
stac_uri = ('s3://rasterfoundry-production-data-us-east-1/stac-exports/'
            'fd478c2b-3f71-41e4-a87b-e97a8a0d0afa/catalog.json')
cat = Catalog.from_file(stac_uri)
'''
# Block A. If this is uncommented, then Line B will fail.
for item in cat.get_all_items():
    print(item)
'''
new_stac_uri = '/opt/data/foo/test-stac-catalog'
cat.normalize_hrefs(new_stac_uri)
cat.save(catalog_type=CatalogType.SELF_CONTAINED)

# Open the local copy and iterate over it.
new_stac_uri = '/opt/data/foo/test-stac-catalog'
cat = Catalog.from_file(join(new_stac_uri, 'catalog.json'))
# Line B
for item in cat.get_all_items():
    print(item)
```

Stack trace:
```shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/foo/pystac_test.py", line 51, in <module>
    for item in cat.get_all_items():
  File "/opt/conda/lib/python3.6/site-packages/pystac/catalog.py", line 281, in get_all_items
    yield from child.get_all_items()
  File "/opt/conda/lib/python3.6/site-packages/pystac/catalog.py", line 281, in get_all_items
    yield from child.get_all_items()
  File "/opt/conda/lib/python3.6/site-packages/pystac/catalog.py", line 279, in get_all_items
    yield from self.get_items()
  File "/opt/conda/lib/python3.6/site-packages/pystac/stac_object.py", line 260, in get_stac_objects
    link.resolve_stac_object(root=self.get_root())
  File "/opt/conda/lib/python3.6/site-packages/pystac/link.py", line 160, in resolve_stac_object
    obj = STAC_IO.read_stac_object(target_href, root=root)
  File "/opt/conda/lib/python3.6/site-packages/pystac/stac_io.py", line 119, in read_stac_object
    return cls.stac_object_from_dict(d, href=uri, root=root)
  File "/opt/conda/lib/python3.6/site-packages/pystac/serialization/__init__.py", line 31, in stac_object_from_dict
    merge_common_properties(d, json_href=href, collection_cache=collection_cache)
  File "/opt/conda/lib/python3.6/site-packages/pystac/serialization/common_properties.py", line 47, in merge_common_properties
    collection = STAC_IO.read_json(collection_href)
  File "/opt/conda/lib/python3.6/site-packages/pystac/stac_io.py", line 96, in read_json
    return json.loads(STAC_IO.read_text(uri))
  File "/opt/conda/lib/python3.6/site-packages/pystac/stac_io.py", line 61, in read_text
    return cls.read_text_method(uri)
  File "/opt/src/foo/pystac_test.py", line 19, in my_read_method
    return STAC_IO.default_read_text_method(uri)
  File "/opt/conda/lib/python3.6/site-packages/pystac/stac_io.py", line 12, in default_read_text_method
    with open(uri) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/foo/test-stac-catalog/12cb17a8-ae08-469c-a2be-4d0619240014/400c22e3-5b54-438b-b600-5e9bd6d0a498/3c67b59c-2e6f-47fb-ba3c-0dd106941096/collection.json'
```

**Comment by lossyrob** [comment]
I've taken the example and narrowed it down to a local test case and unit test. I see there's an issue with the collection HREF being updated when the collection of the item is read in previous to normalize_href (which iterating over the items forces). Still working towards resolving. Thanks for the report!

**Comment by lewfish** [comment]
Thanks, there's no rush because I found a workaround.
